---
- name: Install Redis repos.
  ansible.builtin.yum:
    name: 
      - epel-release
      - yum-utils
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: present
    enablerepo: remi

- name: Update the BindIP
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

#Update the BindIP from 127.0.0.1 to 0.0.0.0 in config file /etc/redis.conf & /etc/redis/redis.conf

- name: Start Redis 
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
