---
- name: Copying SSH key to remote
  hosts: all
  become: yes
  become_user: centos
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: centos
      state: present
      key: "{{ lookup('file', '/home/centos/.ssh/id_rsa.pub') }}"