---
- name: Copy set-hostname script to local
  copy:
    src: set-hostname.sh
    dest: /tmp/

- name: Setting up hostname
  shell: bash /tmp/set-hostname.sh {{ COMPONENT }}

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: centos
    state: present
    key: "{{ lookup('file', '/home/centos/.ssh/id_rsa.pub') }}"


# - name: make direcotry
#   file:
#     path: "/home/{{ ansible_user_id }}/.ssh"
#     state: directory
# - name: create empty file
#   file:
#     path: "/home/{{ ansible_user_id }}/.ssh/authorized_keys"
#     state: touch
# - name: put pubkey
#   lineinfile:
#     path: "/home/{{ ansible_user_id }}/.ssh/authorized_keys"
#     line: "{{ pubkey }}"