---
- name: Install NodeJS packages
  ansible.builtin.yum:
    name: 
      - nodejs
      - make
      - gcc-c++
      - npm   ##TO AVOID a ERROR that saying - Failed to find required executable \"npm\" in paths: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/.local/bin:/root/bin
    state: present

- name: Download task
  include_tasks: download.yml

- name: Node Exporter installation on {{COMPONENT}}
  include_tasks: node_exporter.yml

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/roboshop/{{ COMPONENT }}
    state: present
#  become: yes
  become_user: roboshop

- name: SystemD tasks
  include_tasks: systemd.yml
