---
- name: Install NodeJS packages
  ansible.builtin.yum:
    name: 
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download task
  include_tasks:
    name: download.yml

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/roboshop/{{ COMPONENT }}/package.json
  become_user: roboshop

- name: SystemD tasks
  include_tasks:
    name: systemd.yml

