---
- name: Setup the {{ COMPONENT }} service file
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service
    remote_src: yes

- name: Start {{ COMPONENT }} service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    state: restarted
    enabled: yes
    daemon_reload: yes